# Generated by Django 6.1 on 2026-09-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Facil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDanios',
            fields=[
                ('temblor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reporte_danios', serialize=False, to='app_Facil.temblor')),
                ('afectados', models.IntegerField(default=0)),
                ('descripcion_danios', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='temblor',
            name='lugar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='temblor',
            name='profundidad',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='temblor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temblores', to='app_Facil.departamento'),
        ),
    ]
